apiVersion: v1
kind: Service
metadata:
  name: demok8s-service
  namespace: demok8snamespace  
spec:
  selector:
    app: demok8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  